In [2]:
import numpy as np
import statistics

# Question 1.1
### Calculate the mean for each individual subject.

In [3]:
grades = np.array([
    [11, 9, 16, 13.5],
    [12, 11, 8.5, 10],
    [11, 18, 11.5, 9],
    [7, 15.5, 11, 14],
    [9.5, 12, 10.5, 14],
    [15, 18.5, 7, 12],
    [18, 15.5, 11, 7.5],
])
adam_mean = np.mean(grades[0])
anna_mean = np.mean(grades[1])
james_mean = np.mean(grades[2])
corey_mean = np.mean(grades[3])
alisha_mean = np.mean(grades[4])
jodie_mean = np.mean(grades[5])
john_mean = np.mean(grades[6])

In [4]:
print(adam_mean)
print(anna_mean)
print(james_mean)
print(corey_mean)
print(alisha_mean)
print(jodie_mean)
print(john_mean)

12.375
10.375
12.375
11.875
11.5
13.125
13.0


# Question 1.2
### Find the median grade in Math for all students.

In [5]:
grades_flat = grades.flatten()
grades_sorted = np.sort(grades_flat)
n = len(grades_sorted)
median_index = (n-1)//2
if n % 2 == 1:
    median_grade = grades_sorted[median_index]
else:
    median_grade = (grades_sorted[median_index] + grades_sorted[median_index+1])/2

print(median_grade)


11.25


In [6]:
print(np.median(grades_sorted))

11.25


# Question 1.3
### Calculate the mode for History.

In [7]:
grades_mode = statistics.mode(grades_flat)
print(grades_mode)

11.0


# Question 2
### The strongest correlation is between Math and History


In [8]:
corr_matrix = np.corrcoef(grades[:, :4], rowvar=False)
print(corr_matrix)

[[ 1.          0.2694941  -0.26856189 -0.71835835]
 [ 0.2694941   1.         -0.52760583 -0.35868816]
 [-0.26856189 -0.52760583  1.          0.20679404]
 [-0.71835835 -0.35868816  0.20679404  1.        ]]


# Question 3
### Write a Python function named desc_stats() that takes a list of numbers and prints statistical calculations

In [14]:
def desc_stats(array):
    print(f'Mean: {np.mean(array)}')
    print(f'Median: {np.median(array)}')
    print("Mode:", statistics.mode(array))
    print("Minimum:", np.min(array))
    print("Maximum:", np.max(array))
    print("Range:", np.max(array) - np.min(array))
    print("Variance:", np.var(array, ddof=1))
    print("Standard deviation:", np.std(array, ddof=1))

math_exam_grades = [24, 5, 15, 60, 54, 82, 99, 80, 70, 98, 93, 60, 33, 22, 65, 61, 51, 58, 83, 86, 42, 67, 60]
          
desc_stats(math_exam_grades)


Mean: 59.47826086956522
Median: 60.0
Mode: 60
Minimum: 5
Maximum: 99
Range: 94
Variance: 664.1625708884687
Standard deviation: 26.350555566365703


# Extended Challenge
### Interpret the results. If you were the instructor of the class, would you curve the grade? 

#### I would curve the grade. The average score was basically 60 which is failing and a very high range in scores at 94. 